name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (if using Node.js for build)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
        
      # Step 4: Build the project (inject the secret)
      - name: Build project
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Use your secret here
        run: |
          echo "Building project..."
          npm run build  # Customize as per your build command

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Adjust to your build output directory
