name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Adjust Node.js version as needed

      # Step 3: Ensure Required Directories Exist
      - name: Ensure directories exist
        run: |
          mkdir -p frontend  # Replace 'frontend' with the directory name you want to ensure exists
          mkdir -p build     # Ensure the output build directory exists

      # Step 4: Install dependencies
      - name: Install dependencies
        working-directory: frontend  # Ensure this matches your actual directory structure
        run: npm install

      # Step 5: Build the project
      - name: Build project
        working-directory: frontend  # Ensure this matches your actual directory structure
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build  # Ensure this matches your actual build output directory
